language: objective-c
osx_image: xcode9.2
script:
  - xcodebuild -scheme SwiftExample -workspace SwiftExample.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -t b9be12c6-5fec-4262-b15b-729d2faf9a5f
